// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTEducation.Data.Entities;

#nullable disable

namespace PTEducation.Data.Entities.Migrations
{
    [DbContext(typeof(PteducationContext))]
    [Migration("20260606114504_Update_Database_20260606")]
    partial class Update_Database_20260606
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("ClassScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Fixed");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC07E72A84E8");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassScheduleId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.AttendanceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC079162DFE4");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("AttendanceDetail", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("EndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("StartAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Class__3214EC0762E79B13");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id")
                        .HasName("PK__ClassSch__3214EC077CA59604");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("ExpiredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("isUsed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__OTP__3214EC078544DE14");

                    b.HasIndex("UserId");

                    b.ToTable("OTP", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Shift")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("TestDateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Score__3214EC072819449D");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreateBy");

                    b.ToTable("Score", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ScoreDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<decimal>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__ScoreDet__3214EC07D24DDF71");

                    b.HasIndex("ScoreId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("ScoreDetail", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__StudentC__3214EC07119F651C");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClass", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentGuardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuardianId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__StudentG__3214EC07FC1CC142");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "GuardianId", "StudentId" }, "UQ_StudentGuardians_Student_Guardian")
                        .IsUnique();

                    b.ToTable("StudentGuardians");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValueSql("(NULL)")
                        .HasComment("");

                    b.Property<bool>("IsNeedResetPassword")
                        .HasColumnType("bit")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValueSql("(NULL)")
                        .HasComment("");

                    b.Property<byte[]>("Password")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("PasswordBcrypt")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PasswordBCrypt")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("(NULL)")
                        .HasComment("");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("(NULL)")
                        .HasComment("");

                    b.Property<byte[]>("Salt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)")
                        .HasComment("");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC07FFE4B5D4");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("Attendance_Class_Id_fk");

                    b.HasOne("PTEducation.Data.Entities.ClassSchedule", "ClassSchedule")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassScheduleId")
                        .HasConstraintName("FK_Attendance_ClassSchedule");

                    b.Navigation("Class");

                    b.Navigation("ClassSchedule");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.AttendanceDetail", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Attendance", "Attendance")
                        .WithMany("AttendanceDetails")
                        .HasForeignKey("AttendanceId")
                        .IsRequired()
                        .HasConstraintName("AttendanceDetail_Attendance_Id_fk");

                    b.HasOne("PTEducation.Data.Entities.StudentClass", "StudentClass")
                        .WithMany("AttendanceDetails")
                        .HasForeignKey("StudentClassId")
                        .IsRequired()
                        .HasConstraintName("AttendanceDetail_StudentClass_Id_fk");

                    b.Navigation("Attendance");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "CreatedByNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Class__CreatedBy__46E78A0C");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassSchedule_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Otp", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "User")
                        .WithMany("Otps")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("OTP_User_Id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("Scores")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Score__ClassId__47DBAE45");

                    b.HasOne("PTEducation.Data.Entities.User", "CreateByNavigation")
                        .WithMany("Scores")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK__Score__CreateBy__48CFD27E");

                    b.Navigation("Class");

                    b.Navigation("CreateByNavigation");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ScoreDetail", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Score", "ScoreNavigation")
                        .WithMany("ScoreDetails")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("FK__ScoreDeta__Score__49C3F6B7");

                    b.HasOne("PTEducation.Data.Entities.StudentClass", "StudentClass")
                        .WithMany("ScoreDetails")
                        .HasForeignKey("StudentClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ScoreDeta__Stude__4AB81AF0");

                    b.Navigation("ScoreNavigation");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentCl__Class__4BAC3F29");

                    b.HasOne("PTEducation.Data.Entities.User", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentCl__Stude__4CA06362");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentGuardian", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "Guardian")
                        .WithMany("StudentGuardianGuardians")
                        .HasForeignKey("GuardianId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentGuardians_User_2");

                    b.HasOne("PTEducation.Data.Entities.User", "Student")
                        .WithMany("StudentGuardianStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentGuardians_User");

                    b.Navigation("Guardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.Navigation("AttendanceDetails");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClassSchedules");

                    b.Navigation("Scores");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.Navigation("ScoreDetails");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.Navigation("AttendanceDetails");

                    b.Navigation("ScoreDetails");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Otps");

                    b.Navigation("Scores");

                    b.Navigation("StudentClasses");

                    b.Navigation("StudentGuardianGuardians");

                    b.Navigation("StudentGuardianStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
