// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTEducation.Data.Entities;

#nullable disable

namespace PTEducation.Data.Entities.Migrations
{
    [DbContext(typeof(PteducationContext))]
    [Migration("20260801073356_AddGroupIdToGrade")]
    partial class AddGroupIdToGrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Fixed");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC07F481AFC8");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassScheduleId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.AttendanceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("MakeUpSession")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("StudentClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC070A4C753B");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("MakeUpSession");

                    b.HasIndex("StudentClassId");

                    b.ToTable("AttendanceDetail", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Chat__3214EC07665A0511");

                    b.HasIndex("ClassId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("JoinedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__ChatDeta__3214EC07BDD868E3");

                    b.HasIndex("ChatId");

                    b.HasIndex("LastReadMessageId");

                    b.HasIndex(new[] { "UserId" }, "IX_ChatDetail_UserId");

                    b.ToTable("ChatDetail", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<Guid>("SenderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ChatMess__3214EC07E092441E");

                    b.HasIndex("SenderDetailId");

                    b.HasIndex(new[] { "ChatId", "CreatedAt" }, "IX_ChatMessage_ChatId_CreatedAt");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Class__3214EC078308503B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GradeId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id")
                        .HasName("PK__ClassSch__3214EC077CA59604");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Grade__3214EC07BC8F26CF");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("isUsed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__OTP__3214EC07C63E98B9");

                    b.HasIndex("UserId");

                    b.ToTable("OTP", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Shift")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TestDateAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Score__3214EC07ACF5C81E");

                    b.HasIndex("ClassId");

                    b.ToTable("Score", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ScoreDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("StudentClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ScoreDet__3214EC07E01EB94E");

                    b.HasIndex("ScoreId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("ScoreDetail", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__StudentC__3214EC078425ABAC");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClass", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentGuardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuardianId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__StudentG__3214EC0713CAFB4B");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "GuardianId", "StudentId" }, "UQ_StudentGuardians_Student_Guardian")
                        .IsUnique();

                    b.ToTable("StudentGuardians");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentTuition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Unpaid");

                    b.Property<Guid>("StudentClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuitionPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentT__3214EC079B29F240");

                    b.HasIndex("StudentClassId");

                    b.HasIndex(new[] { "PaymentStatus" }, "IX_StudentTuition_Status");

                    b.HasIndex(new[] { "TuitionPeriodId", "StudentClassId" }, "UQ_StudentTuition_Period_Student")
                        .IsUnique();

                    b.ToTable("StudentTuition", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.TuitionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__TuitionP__3214EC078178108C");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GradeId");

                    b.ToTable("TuitionPeriod", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsNeedResetPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordBcrypt")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PasswordBCrypt");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SchoolInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC073E0D4F3B");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Att_Class");

                    b.HasOne("PTEducation.Data.Entities.ClassSchedule", "ClassSchedule")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassScheduleId")
                        .HasConstraintName("FK_Att_CS");

                    b.Navigation("Class");

                    b.Navigation("ClassSchedule");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.AttendanceDetail", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Attendance", "Attendance")
                        .WithMany("AttendanceDetailAttendances")
                        .HasForeignKey("AttendanceId")
                        .IsRequired()
                        .HasConstraintName("FK_AD_Att");

                    b.HasOne("PTEducation.Data.Entities.Attendance", "MakeUpSessionNavigation")
                        .WithMany("AttendanceDetailMakeUpSessionNavigations")
                        .HasForeignKey("MakeUpSession")
                        .HasConstraintName("FK_AD_Att_01");

                    b.HasOne("PTEducation.Data.Entities.StudentClass", "StudentClass")
                        .WithMany("AttendanceDetails")
                        .HasForeignKey("StudentClassId")
                        .IsRequired()
                        .HasConstraintName("FK_AD_SC");

                    b.Navigation("Attendance");

                    b.Navigation("MakeUpSessionNavigation");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Chat", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("Chats")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Chat_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatDetail", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Chat", "Chat")
                        .WithMany("ChatDetails")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK_CD_Chat");

                    b.HasOne("PTEducation.Data.Entities.ChatMessage", "LastReadMessage")
                        .WithMany("ChatDetails")
                        .HasForeignKey("LastReadMessageId")
                        .HasConstraintName("FK_CD_LastRead");

                    b.HasOne("PTEducation.Data.Entities.User", "User")
                        .WithMany("ChatDetails")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CD_User");

                    b.Navigation("Chat");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK_CM_Chat");

                    b.HasOne("PTEducation.Data.Entities.ChatDetail", "SenderDetail")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_CM_SenderDetail");

                    b.Navigation("Chat");

                    b.Navigation("SenderDetail");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "CreatedByNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Class_User");

                    b.HasOne("PTEducation.Data.Entities.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Grade");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_CS_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Otp", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "User")
                        .WithMany("Otps")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_OTP_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("Scores")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Score_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ScoreDetail", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Score", "ScoreNavigation")
                        .WithMany("ScoreDetails")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("FK_SD_Score");

                    b.HasOne("PTEducation.Data.Entities.StudentClass", "StudentClass")
                        .WithMany("ScoreDetails")
                        .HasForeignKey("StudentClassId")
                        .IsRequired()
                        .HasConstraintName("FK_SD_SC");

                    b.Navigation("ScoreNavigation");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_SC_Class");

                    b.HasOne("PTEducation.Data.Entities.User", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SC_User");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentGuardian", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "Guardian")
                        .WithMany("StudentGuardianGuardians")
                        .HasForeignKey("GuardianId")
                        .IsRequired()
                        .HasConstraintName("FK_SG_Guardian");

                    b.HasOne("PTEducation.Data.Entities.User", "Student")
                        .WithMany("StudentGuardianStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SG_Student");

                    b.Navigation("Guardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentTuition", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.StudentClass", "StudentClass")
                        .WithMany("StudentTuitions")
                        .HasForeignKey("StudentClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ST_StudentClass");

                    b.HasOne("PTEducation.Data.Entities.TuitionPeriod", "TuitionPeriod")
                        .WithMany("StudentTuitions")
                        .HasForeignKey("TuitionPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_ST_Period");

                    b.Navigation("StudentClass");

                    b.Navigation("TuitionPeriod");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.TuitionPeriod", b =>
                {
                    b.HasOne("PTEducation.Data.Entities.User", "CreatedByNavigation")
                        .WithMany("TuitionPeriods")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Period_User");

                    b.HasOne("PTEducation.Data.Entities.Grade", "Grade")
                        .WithMany("TuitionPeriods")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("FK_Period_Grade");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Attendance", b =>
                {
                    b.Navigation("AttendanceDetailAttendances");

                    b.Navigation("AttendanceDetailMakeUpSessionNavigations");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Chat", b =>
                {
                    b.Navigation("ChatDetails");

                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatDetail", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ChatMessage", b =>
                {
                    b.Navigation("ChatDetails");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Class", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Chats");

                    b.Navigation("ClassSchedules");

                    b.Navigation("Scores");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.ClassSchedule", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TuitionPeriods");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.Score", b =>
                {
                    b.Navigation("ScoreDetails");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.StudentClass", b =>
                {
                    b.Navigation("AttendanceDetails");

                    b.Navigation("ScoreDetails");

                    b.Navigation("StudentTuitions");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.TuitionPeriod", b =>
                {
                    b.Navigation("StudentTuitions");
                });

            modelBuilder.Entity("PTEducation.Data.Entities.User", b =>
                {
                    b.Navigation("ChatDetails");

                    b.Navigation("Classes");

                    b.Navigation("Otps");

                    b.Navigation("StudentClasses");

                    b.Navigation("StudentGuardianGuardians");

                    b.Navigation("StudentGuardianStudents");

                    b.Navigation("TuitionPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
